import "./globals.css";
import { Navbar } from "../components/shares/Nav";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Trackee",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='flex flex-col min-h-screen'>
        <main className='relative overflow-hidden bg_dashboard flex-1'>
          {children}
        </main>
        <Navbar />
        <ToastContainer />
      </body>
    </html>
  );
}
